<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\SideCursor.ico</ApplicationIcon>
    <AssemblyName>SideCursor.Windows</AssemblyName>
    <RootNamespace>SideCursor.Windows</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\SideCursor.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.5.1" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>
</Project>
